'use client'

import { useState } from 'react'
import { Send, Bot, User, FileText, Code } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { ScrollArea } from '@/components/ui/scroll-area'
import { cn } from '@/lib/utils'

interface Message {
  id: string
  role: 'user' | 'assistant'
  content: string
}

const mockMessages: Message[] = [
  {
    id: '1',
    role: 'user',
    content: 'Tell me about your experience with Next.js.',
  },
  {
    id: '2',
    role: 'assistant',
    content: 'I have extensive experience with Next.js, including App Router, Server Actions, and optimizing for performance. I built this portfolio using Next.js 14.',
  },
]

const mockRagContext = `
# Retrieved Context

## Experience: Senior Engineer
**Source:** User (High Confidence)
- Developed multiple high-traffic applications using Next.js.
- Migrated legacy React apps to Next.js App Router.

## Project: AutoFolio
**Source:** AI Generated
- A portfolio application built with Next.js, Tailwind, and Supabase.
- Uses Vercel AI SDK for chat functionality.
`

export default function AdminChatPage() {
  const [messages, setMessages] = useState<Message[]>(mockMessages)
  const [input, setInput] = useState('')

  const handleSendMessage = (e: React.FormEvent) => {
    e.preventDefault()
    if (!input.trim()) return

    const newMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: input,
    }

    setMessages([...messages, newMessage])
    setInput('')

    // Simulate AI response
    setTimeout(() => {
      setMessages((prev) => [
        ...prev,
        {
          id: (Date.now() + 1).toString(),
          role: 'assistant',
          content: 'This is a simulated response. In the real implementation, this would be generated by the AI model using the context on the right.',
        },
      ])
    }, 1000)
  }

  return (
    <div className="flex h-[calc(100vh-8rem)] gap-4 overflow-hidden">
      {/* Left Pane: Chat Interface */}
      <section className="flex flex-1 flex-col rounded-xl border bg-background shadow-sm">
        <header className="flex h-14 items-center border-b px-4">
          <h2 className="text-lg font-semibold flex items-center gap-2">
            <Bot className="h-5 w-5 text-primary" />
            Admin Chat Simulator
          </h2>
        </header>

        <ScrollArea className="flex-1 p-4">
          <div className="flex flex-col gap-4">
            {messages.map((m) => (
              <div
                key={m.id}
                className={cn(
                  "flex gap-3 max-w-[80%]",
                  m.role === 'user' ? "ml-auto flex-row-reverse" : ""
                )}
              >
                <div className={cn(
                  "flex h-8 w-8 shrink-0 items-center justify-center rounded-full border",
                  m.role === 'user' ? "bg-primary text-primary-foreground" : "bg-muted"
                )}>
                  {m.role === 'user' ? <User className="h-4 w-4" /> : <Bot className="h-4 w-4" />}
                </div>
                <div className={cn(
                  "rounded-lg px-3 py-2 text-sm",
                  m.role === 'user' ? "bg-primary text-primary-foreground" : "bg-muted"
                )}>
                  {m.content}
                </div>
              </div>
            ))}
          </div>
        </ScrollArea>

        <div className="border-t p-4">
          <form onSubmit={handleSendMessage} className="flex gap-2">
            <Input
              placeholder="Type a message to test..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
              className="flex-1"
            />
            <Button type="submit" size="icon">
              <Send className="h-4 w-4" />
            </Button>
          </form>
        </div>
      </section>

      {/* Right Pane: RAG Preview */}
      <section className="hidden w-[400px] flex-col rounded-xl border bg-muted/30 lg:flex">
        <header className="flex h-14 items-center justify-between border-b px-4 bg-background/50">
          <h2 className="text-lg font-semibold flex items-center gap-2">
            <FileText className="h-5 w-5 text-muted-foreground" />
            Context Preview
          </h2>
          <Button variant="ghost" size="icon" title="View Raw JSON">
            <Code className="h-4 w-4" />
          </Button>
        </header>
        <ScrollArea className="flex-1 p-4">
          <div className="prose prose-sm dark:prose-invert">
            <pre className="whitespace-pre-wrap font-mono text-xs text-muted-foreground">
              {mockRagContext}
            </pre>
          </div>
          <div className="mt-4 rounded-md border bg-background p-3">
            <h3 className="mb-2 text-xs font-semibold uppercase text-muted-foreground">
              Retrieval Stats
            </h3>
            <div className="grid gap-1 text-xs">
              <div className="flex justify-between">
                <span>Documents Found:</span>
                <span className="font-medium">2</span>
              </div>
              <div className="flex justify-between">
                <span>Latency:</span>
                <span className="font-medium">45ms</span>
              </div>
            </div>
          </div>
        </ScrollArea>
      </section>
    </div>
  )
}
